const translationsEn = {
    portfolio_title: "My Portfolio",
    about: "About Me",
    skills: "Skills",
    experience: "Experience",
    contact: "Contact",
    about_intro: "A young programmer with almost 3 years of experience, not afraid of challenges and eager to learn. The main programming language I used in my previous company was PHP, but I am no stranger to writing scripts in JavaScript or styling pages in CSS. I have experience with design patterns, including MVC, and writing readable, understandable and maintainable code in accordance with the Clean Code principles. I am also a 3rd year computer science student at DSW University. I am eager to learn new things and I am very inquisitive. As a hobby, I also create simple games in Unreal Engine and Unity.",
    langBtn: "🇵🇱 Polski",
    skills_php7: "PHP7+", 
    skills_oop: "OOP", 
    skills_sql: "SQL", 
    skills_javascript: "JavaScript", 
    skills_html: "HTML", 
    skills_css: "CSS", 
    skills_bootstrap: "Bootstrap", 
    skills_tailwindcss: "Tailwind CSS", 
    skills_gitlab: "GitLab", 
    skills_github: "GitHub", 
    skills_ue5: "Unreal Engine 5", 
    skills_unity: "Unity", 
    experience_job_db: "Database designer",
    experience_where_db: "City and Commune Office in Ostrzeszów",
    experience_job_phpdev: "Junior PHP Developer",
    experience_where_phpdev: "Inbs.Software Konrad Keck",
    experience_when_phpdev: "08/05/2022 – 31/03/2025 | Rzeszów (Remote work), Poland",
    experience_desc_db_db: "Designing a database in Excel containing all conclusions and decisions",
    experience_desc_phpdev_clients: "Creating and developing modules according to customer requirements",
    experience_desc_phpdev_repair: "Repair and optimization of existing modules",
    experience_desc_phpdev_docs: "Creating design documentation",
    experience_desc_phpdev_plans: "Suggesting and implementing improvements",
    contact_address: 'Rogaszyce ul. Żyrowska 44',
    contact_email_address: 'lukasz.rybarz12@gmail.com',
    contact_telephone_number: '+48 883 842 077',
    contact_facebook: 'facebook.com',
    contact_github: 'github.com',
    contact_linkedin: 'linkedin.com',
    copyright: "Łukasz. All rights reserved.",
};

export default translationsEn;
