const translationsEn = {
    portfolio_title: "My Portfolio",
    about: "About Me",
    skills: "Skills",
    experience: "Experience",
    contact: "Contact",
    about_intro: "Hi! My name is Łukasz and I am a young programmer with almost 3 years of experience, not afraid of challenges and eager to learn. The main programming language I used in my previous company was PHP, but I am familiar with writing scripts in JavaScript or styling pages in CSS. I have experience with design patterns, including MVC, and in writing readable, understandable and maintainable code in accordance with the principles of Clean Code. I am also a student of computer science 3rd year at DSW University. I am eager to learn new things and I am very inquisitive. I also create simple games in Unreal Engine and Unity.",    langBtn: "🇵🇱 Polski",
    skills_php7: "PHP7+", 
    skills_oop: "OOP", 
    skills_sql: "SQL", 
    skills_javascript: "JavaScript", 
    skills_html: "HTML", 
    skills_css: "CSS", 
    skills_bootstrap: "Bootstrap", 
    skills_tailwindcss: "Tailwind CSS", 
    skills_gitlab: "GitLab", 
    skills_github: "GitHub", 
    skills_ue5: "Unreal Engine 5", 
    skills_unity: "Unity", 
    skills_vue: "Vue.js",
    experience_job_db: "Database designer",
    experience_where_db: "City and Commune Office in Ostrzeszów",
    experience_job_phpdev: "Junior PHP Developer",
    experience_where_phpdev: "Inbs.Software Konrad Keck",
    experience_when_phpdev: "05/2022 – 03/2025 | Rzeszów (Remote work), Poland",
    experience_desc_db_db: "Designing a database in Excel containing all conclusions and decisions",
    experience_desc_phpdev_clients: "Creating and developing modules according to customer requirements",
    experience_desc_phpdev_repair: "Repair and optimization of existing modules",
    experience_desc_phpdev_docs: "Creating design documentation",
    experience_desc_phpdev_plans: "Suggesting and implementing improvements",
    contact_address: '63-500 Rogaszyce',
    contact_email_address: 'lukasz.rybarz12@gmail.com',
    contact_telephone_number: '+48 883 842 077',
    contact_facebook: 'facebook.com',
    contact_github: 'github.com',
    contact_linkedin: 'linkedin.com',
    copyright: "Łukasz. All rights reserved.",
    experience_job_bigcom: "PrestaShop Developer",
    experience_where_bigcom: "BigCom, Rzeszów",
    experience_when_bigcom: "04/2025 | Rzeszów, Poland",
    experience_desc_bigcom_module: "Developing a module for PrestaShop",
    experience_desc_bigcom_integration: "Integrating the module with the existing application",
    experience_desc_bigcom_tests: "Conducting functional and unit tests",
    experience_desc_bigcom_optimization: "Optimizing code for performance",
    experience_desc_bigcom_docs: "Preparing user and deployment documentation",
    experience_desc_bigcom_deployment: "Deploying the module to the production environment",
    experience_job_kislist: "PHP Developer",
    experience_where_kislist: "Kislist, Warsaw",
    experience_when_kislist: "05/2025 – 06/2025",
    experience_desc_kislist_design: "Designing and implementing new application modules according to user requirements",
    experience_desc_kislist_api: "Adapting the application to changing internal requirements",
    experience_desc_kislist_impl: "Implementing new options and features in the plugin",
    experience_desc_kislist_opt: "Ensuring plugin functionality with main app and target environment, optimization",
    experience_desc_kislist_docs: "Preparing user documentation and implementation instructions",
    experience_desc_kislist_tests: "Testing the plugin and its features",
};

export default translationsEn;
