const translationsPl = {
    portfolio_title: "Moje Portfolio",
    about: "O mnie",
    skills: "Umiejętności",
    experience: "Doświadczenie",
    contact: "Kontakt",
    about_intro: "Cześć! Nazywam się Łukasz i jestem młodym programistą z prawie 3-letnim stażem, niebojącym się wyzwań oraz z zapałem do nauki. Głównym językiem programowania, którym operowałem w poprzedniej firmie, było PHP, jednak nie jest mi obce pisanie skryptów w JavaScript czy stylowanie stron w CSS. Posiadam doświadczenie ze wzorcami projektowymi, między innymi MVC, oraz w pisaniu czytelnego, zrozumiałego  i utrzymywalnego kodu zgodnie z zasadami Clean Code. Jestem również studentem informatyki 3. roku na Uniwersytecie DSW.  Chętnie uczę się nowych rzeczy oraz jestem bardzo dociekliwy. Hobbistycznie tworzę też proste gry w silnikach Unreal Engine oraz Unity.",
    langBtn: "🇬🇧 English",
    skills_php7: "PHP7+", 
    skills_oop: "OOP", 
    skills_sql: "SQL", 
    skills_javascript: "JavaScript", 
    skills_html: "HTML", 
    skills_css: "CSS", 
    skills_bootstrap: "Bootstrap", 
    skills_tailwindcss: "Tailwind CSS", 
    skills_gitlab: "GitLab", 
    skills_github: "GitHub", 
    skills_ue5: "Unreal Engine 5", 
    skills_unity: "Unity", 
    experience_job_db: "Projektant baz danych",
    experience_where_db: "Urząd Miasta i Gminy w Ostrzeszowie",
    experience_when_db: "[ 04/05/2021 – 31/05/2021 ] Ostrzeszów, Polska",
    experience_job_phpdev: "Junior PHP Developer",
    experience_where_phpdev: "Inbs.Software Konrad Keck",
    experience_when_phpdev: "[ 08/05/2022 – 31/03/2025 ] Rzeszów (Praca zdalna), Polska",
    experience_desc_db_db: "Zaprojektowanie bazy danych w Excelu, zawierającej wszystkie wnioski i decyzje",
    experience_desc_phpdev_clients: "Tworzenie i rozwijanie modułów według wymagań klientów",
    experience_desc_phpdev_repair: "Naprawa i optymalizacja istniejących modułów",
    experience_desc_phpdev_docs: "Tworzenie dokumentacji projektowej",
    experience_desc_phpdev_plans: "Proponowanie oraz wdrażanie usprawnień",
    contact_address: '63-500 Rogaszyce',
    contact_email_address: 'lukasz.rybarz12@gmail.com',
    contact_telephone_number: '+48 883 842 077',
    contact_facebook: 'facebook.com',
    contact_github: 'github.com',
    contact_linkedin: 'linkedin.com',
    copyright: "Łukasz. Wszelkie prawa zastrzeżone.",
};

export default translationsPl;
