const translationsPl = {
    portfolio_title: "Moje Portfolio",
    about: "O mnie",
    skills: "Umiejętności",
    experience: "Doświadczenie",
    contact: "Kontakt",
    about_intro: "Cześć! Nazywam się Łukasz i jestem młodym programistą z prawie 3-letnim stażem, niebojącym się wyzwań oraz z zapałem do nauki. Głównym językiem programowania, którym operowałem w poprzedniej firmie, było PHP, jednak nie jest mi obce pisanie skryptów w JavaScript czy stylowanie stron w CSS. Dysponuję także doświadczeniem w pracy z API, między innymi takimi serwisami jak Plesk, Cpanel, Hetzner czy DirectAdmin. Z sukcesem stworzyłem również w 100% działającą integrację systemu WHMCS z platformą Google Analytics 4 oraz współtworzyłem wiele innych modułów. Posiadam doświadczenie ze wzorcami projektowymi, między innymi MVC, oraz w pisaniu czytelnego, zrozumiałego  i utrzymywalnego kodu zgodnie z zasadami Clean Code. Jestem również studentem informatyki 3. roku na Uniwersytecie DSW.  Chętnie uczę się nowych rzeczy oraz jestem bardzo dociekliwy. Hobbistycznie tworzę też proste gry w silnikach Unreal Engine oraz Unity.",
    skills_php7: "PHP7+", 
    skills_oop: "OOP", 
    skills_sql: "SQL", 
    skills_javascript: "JavaScript", 
    skills_html: "HTML", 
    skills_css: "CSS", 
    skills_bootstrap: "Bootstrap", 
    skills_tailwindcss: "Tailwind CSS", 
    skills_gitlab: "GitLab", 
    skills_github: "GitHub", 
    skills_ue5: "Unreal Engine 5", 
    skills_unity: "Unity", 
    skills_vue: "Vue.js",
    experience_job_db: "Projektant baz danych",
    experience_where_db: "Urząd Miasta i Gminy w Ostrzeszowie",
    experience_when_db: "[ 04/05/2021 – 31/05/2021 ] Ostrzeszów, Polska",
    experience_job_phpdev: "Junior PHP Developer",
    experience_where_phpdev: "Inbs.Software Konrad Keck",
    experience_when_phpdev: "05/2022 – 03/2025 | Rzeszów (Praca zdalna), Polska",
    experience_desc_db_db: "Zaprojektowanie bazy danych w Excelu, zawierającej wszystkie wnioski i decyzje",
    experience_desc_phpdev_clients: "Tworzenie i rozwijanie modułów według wymagań klientów",
    experience_desc_phpdev_repair: "Naprawa i optymalizacja istniejących modułów",
    experience_desc_phpdev_docs: "Tworzenie dokumentacji projektowej",
    experience_desc_phpdev_plans: "Proponowanie oraz wdrażanie usprawnień",
    experience_desc_phpdev_apis: "Projektowanie i wdrażanie integracji WHMCS z serwisami takimi jak Plesk, cPanel, Hetzner czy DirectAdmin przy użyciu ich API",
    contact_address: '63-500 Rogaszyce',
    contact_email_address: 'lukasz.rybarz12@gmail.com',
    contact_telephone_number: '+48 883 842 077',
    contact_facebook: 'facebook.com',
    contact_github: 'github.com',
    contact_linkedin: 'linkedin.com',
    copyright: "Łukasz. Wszelkie prawa zastrzeżone.",
    experience_job_bigcom: "Programista PrestaShop",
    experience_where_bigcom: "BigCom, Rzeszów",
    experience_when_bigcom: "04/2025 | Rzeszów, Polska",
    experience_desc_bigcom_module: "Tworzenie modułu do PrestaShop",
    experience_desc_bigcom_integration: "Integracja modułu z istniejącą aplikacją",
    experience_desc_bigcom_tests: "Przeprowadzanie testów funkcjonalnych i jednostkowych",
    experience_desc_bigcom_optimization: "Optymalizacja kodu pod kątem wydajności",
    experience_desc_bigcom_docs: "Przygotowywanie dokumentacji użytkownika i wdrożeniowej",
    experience_desc_bigcom_deployment: "Wdrożenie modułu na środowisko produkcyjne",
    experience_job_kislist: "PHP Developer",
    experience_where_kislist: "Kislist, Warszawa",
    experience_when_kislist: "05/2025 – 06/2025",
    experience_desc_kislist_design: "Projektowanie i wdrażanie nowych modułów aplikacji zgodnie z wymaganiami użytkowników",
    experience_desc_kislist_api: "Dostosowywanie aplikacji do zmieniających się wewnętrznych wymagań",
    experience_desc_kislist_impl: "Implementacja nowych opcji i funkcji w wtyczce",
    experience_desc_kislist_opt: "Zapewnienie funkcjonalności wtyczki z główną aplikacją i środowiskiem docelowym oraz optymalizacja",
    experience_desc_kislist_docs: "Przygotowywanie dokumentacji użytkownika i instrukcji wdrożenia",
    experience_desc_kislist_tests: "Testowanie wtyczki i funkcjonalności",
};

export default translationsPl;
